echo -e "Puedes acceder a la máquina a través del siguiente comando:"
echo "------------------DEGUG--------------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init-output.log\""
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init.log\""
echo "-------------------------------------------"
echo "--------------CONECTAR SSH-----------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP"
echo "--------------CONECTAR SSM-----------------"
echo "aws --profile $AWS_PROFILE --region $AWS_REGION ssm start-session --target $INSTANCE_ID"
echo "-------------------------------------------"
echo "-----------------NAVEGADOR-----------------"
echo "http://$PUBLIC_IP/ | http://${DOMAIN_NAME-unset}/"
echo "https://$PUBLIC_IP/ | https://${DOMAIN_NAME-unset}/"
echo "-------------------------------------------"