echo -e "Puedes acceder a la máquina a través del siguiente comando:"
echo "------------------DEGUG--------------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init-output.log\""
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init.log\""
echo "-------------------------------------------"
echo "------------------CONECTAR-----------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP"
echo "-------------------------------------------"
echo "-----------------NAVEGADOR-----------------"
echo "http://$PUBLIC_IP/ |" 
echo "https://$PUBLIC_IP/ |" 
echo "-------------------------------------------"