echo -e "Puedes acceder a la máquina a través del siguiente comando:"
echo "------------------DEGUG--------------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init-output.log\""
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP \"cat /var/log/cloud-init.log\""
echo "aws ssm start-session --profile $AWS_PROFILE --region $AWS_REGION --target $INSTANCE_ID --document-name \"AWS-StartInteractiveCommand\" --parameters 'commands=[\"cat /var/log/cloud-init-output.log\"]'"
echo "aws ssm start-session --profile $AWS_PROFILE --region $AWS_REGION --target $INSTANCE_ID --document-name \"AWS-StartInteractiveCommand\" --parameters 'commands=[\"cat /var/log/cloud-init.log\"]'"
echo "-------------------------------------------"
echo "--------------CONECTAR SSH-----------------"
echo "ssh -i $PEM_KEY_REALPATH ubuntu@$PUBLIC_IP"
echo "--------------CONECTAR SSM-----------------"
echo "aws --profile $AWS_PROFILE --region $AWS_REGION ssm start-session --target $INSTANCE_ID"
echo "-------------------------------------------"
echo "-----------PORT FORWARDING SSM-------------"
echo "aws --profile $AWS_PROFILE --region $AWS_REGION ssm start-session --target $INSTANCE_ID --document-name AWS-StartPortForwardingSession --parameters 'portNumber=5432,localPortNumber=5432'"
echo "-----------PORT FORWARDING SSH-------------"
echo "ssh -i $PEM_KEY_REALPATH -L 5432:localhost:5432 ubuntu@$PUBLIC_IP -N -f"
echo "-------------------------------------------"
echo "-------------------PSQL--------------------"
echo "psql -H $PUBLIC_IP -U postgres"
echo "-------------------------------------------"
echo "-----------------NAVEGADOR-----------------"
echo "http://$PUBLIC_IP/ | http://${DOMAIN_NAME-unset}/"
echo "https://$PUBLIC_IP/ | https://${DOMAIN_NAME-unset}/"
echo "-------------------------------------------"